services:
  frontend:
    build: .
    container_name: cardinal-frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3004:3004"
    networks:
      - cardinal-net

networks:
  cardinal-net:
    external: true
