/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SafesendRouteImport } from './routes/safesend'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'

const SafesendRoute = SafesendRouteImport.update({
  id: '/safesend',
  path: '/safesend',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/partners': typeof PartnersRoute
  '/pilot': typeof PilotRoute
  '/safesend': typeof SafesendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/partners': typeof PartnersRoute
  '/pilot': typeof PilotRoute
  '/safesend': typeof SafesendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/partners': typeof PartnersRoute
  '/pilot': typeof PilotRoute
  '/safesend': typeof SafesendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/partners' | '/pilot' | '/safesend'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/partners' | '/pilot' | '/safesend'
  id: '__root__' | '/' | '/app' | '/partners' | '/pilot' | '/safesend'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  PartnersRoute: typeof PartnersRoute
  PilotRoute: typeof PilotRoute
  SafesendRoute: typeof SafesendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/safesend': {
      id: '/safesend'
      path: '/safesend'
      fullPath: '/safesend'
      preLoaderRoute: typeof SafesendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  PartnersRoute: PartnersRoute,
  PilotRoute: PilotRoute,
  SafesendRoute: SafesendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
